apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: cluster-deployment-customimageset-template

parameters:
- name: IMAGE
  displayName: Container Image
  description: The container image to use for the deployment
  required: true

- name: NAMESPACE
  displayName: Namespace
  description: Namespace to deploy objects
  required: true

objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      name: "${NAMESPACE}"
    name: "${NAMESPACE}"

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ose
    labels:
      run: ose
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: ose
    template:
      metadata:
        labels:
          run: ose
      spec:
        containers:
          - name: ose
            image: '${IMAGE}'
            env:
              - name: REGISTRY_OPENSHIFT_SERVER_ADDR
                value: 10.0.0.1
            ports:
              - containerPort: 5000
                protocol: TCP
            readinessProbe:
              failureThreshold: 3
              tcpSocket:
                port: 5000
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
            livenessProbe:
              failureThreshold: 3
              tcpSocket:
                port: 5000
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
